name: PHP Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
      run: composer validate

    - name: Install dependencies
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run tests
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'
      run: ./vendor/phpunit/phpunit/phpunit ./tests/
